### PR TITLE
CML workflow updates (bis)

### PR DESCRIPTION
**Pull request by 0x2b3bfa0**
Follow–up of #8

### CODE REVIEW

**Comment by alex000kim** [comment]
Thanks @0x2b3bfa0 !
Do you know why `train-model` stage failed?
https://github.com/iterative/magnetic-tiles-defect/runs/5823721561?check_suite_focus=true#step:8:329

**Comment by 0x2b3bfa0** [comment]
Sounds like some obscure DVC error related to `pyinstaller` 🤔

**Comment by alex000kim** [comment]
5928755

## Metrics
| Path                  | acc_mean   | dice.multi   | dice_mean   | epoch   | foreground.acc   | jaccard.coeff   | step   | train.loss   | valid.loss   |
|-----------------------|------------|--------------|-------------|---------|------------------|-----------------|--------|--------------|--------------|
| training_metrics.json | -          | 0.85638      | -           | 11.0    | 0.62449          | 0.58449         | 12     | 0.09522      | 0.12971      |
| metrics.json          | 0.96794    | -            | 0.73394     | -       | -                | -               | -      | -            | -            |

## A few random test images






















CML watermark

**Comment by 0x2b3bfa0** [comment]
@alex000kim, https://github.com/iterative/dvc/issues/7542

**Comment by 0x2b3bfa0** [comment]
@alex000kim, that's a known issue in DVC, and isn't related to this pull request:
* https://github.com/iterative/dvc/issues/7531

**Pull request merged**
